kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-2-pvc
  namespace: generate-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: ibmc-file-bronze-gid
  volumeMode: Filesystem
